#!/bin/bash

echo "🔥 Firebase Setup Helper for Cashora"
echo "===================================="
echo ""
echo "This script will help you set up Firebase authentication."
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "✅ .env file found"
else
    echo "❌ .env file not found"
    echo "Creating .env from template..."
    cp .env.example .env
    echo "✅ .env file created"
fi

echo ""
echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo ""
echo "1️⃣  Open Firebase Console:"
echo "    👉 https://console.firebase.google.com/"
echo ""
echo "2️⃣  Create or select your project"
echo ""
echo "3️⃣  Click the Web icon (</>) to add a web app"
echo ""
echo "4️⃣  You'll see a config object like this:"
echo ""
echo "    const firebaseConfig = {"
echo "      apiKey: \"AIzaSy...\","
echo "      authDomain: \"your-project.firebaseapp.com\","
echo "      projectId: \"your-project-id\","
echo "      storageBucket: \"your-project.appspot.com\","
echo "      messagingSenderId: \"123456789\","
echo "      appId: \"1:123456789:web:abc123\""
echo "    };"
echo ""
echo "5️⃣  Copy each value and paste it into your .env file"
echo ""
echo "6️⃣  Enable Google Sign-In:"
echo "    - Go to Authentication > Sign-in method"
echo "    - Click on Google"
echo "    - Toggle Enable"
echo "    - Select support email"
echo "    - Click Save"
echo ""
echo "7️⃣  Restart your dev server:"
echo "    - Press Ctrl+C to stop"
echo "    - Run: npm run dev"
echo ""
echo "📝 Your .env file location: $(pwd)/.env"
echo ""
echo "Need help? Check these guides:"
echo "  - Quick setup: SETUP_GOOGLE_AUTH.md"
echo "  - Detailed guide: FIREBASE_SETUP.md"
echo ""
echo "🎉 Once configured, visit: http://localhost:8080/login"
echo ""
